### ISSUE TITLE
你可能不知道的 Date 类 | 小冷的备忘录

### ISSUE THREAD

**Issue by x-cold** [x-cold/HexoBlog-resource-x-cold#9]
http://blog.lxstart.net/2017/12/17/%E4%BD%A0%E5%8F%AF%E8%83%BD%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84-Date-%E7%B1%BB/

**Comment by rccoder** [comment]
- new Date('xx-xx-xx') 这种写法比较坑，在低版本浏览器中都存在问题，换成 `/` 更好
- Date 中感觉最难理解是时区问题了，尤其是对我这种没出过国的 😂
